# Generated by Django 2.2.3 on 2019-07-12 00:16

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=10)),
                ('examples', django_mysql.models.ListTextField(models.CharField(max_length=400), max_length=10, size=None)),
                ('notes', django_mysql.models.ListTextField(models.CharField(max_length=400), max_length=10, size=None)),
                ('test_status', models.IntegerField(default=0)),
                ('test_number', models.IntegerField(default=0)),
            ],
        ),
    ]
