# Generated by Django 2.2.3 on 2019-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(default='', max_length=200)),
                ('language', models.CharField(default='English', max_length=10)),
                ('test_status', models.IntegerField(default=0)),
                ('test_number', models.IntegerField(default=0)),
            ],
        ),
    ]
