# Generated by Django 2.2.3 on 2019-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='word',
            name='notes',
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(default='English', max_length=10),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='', max_length=200),
        ),
    ]
